const profesionesPorRubro = {
  Tecnologia: [
    'Desarrollador de software',
    'Ingeniero de sistemas',
    'Analista de datos',
    'Diseñador UX/UI',
    'Especialista en ciberseguridad',
  ],
  Salud: [
    'Médico',
    'Enfermero/a',
    'Fisioterapeuta',
    'Psicólogo/a',
    'Nutricionista',
  ],
  Educación: [
    'Profesor/a de primaria',
    'Profesor/a de secundaria',
    'Profesor/a de universidad',
    'Educador/a infantil',
    'Pedagogo/a',
  ],
  Gastronomía: ['Chef', 'Cocinero/a', 'Pastelero/a', 'Panadero/a', 'Sommelier'],
  Diseño: [
    'Diseñador gráfico',
    'Diseñador de moda',
    'Diseñador de interiores',
    'Diseñador web',
    'Ilustrador/a',
  ],
  Arte: [
    'Pintor/a',
    'Escultor/a',
    'Artista multimedia',
    'Fotógrafo/a',
    'Artista digital',
  ],
  Deporte: [
    'Entrenador/a personal',
    'Preparador/a físico/a',
    'Fisioterapeuta deportivo/a',
    'Nutricionista deportivo/a',
    'Árbitro/a',
  ],
  Moda: [
    'Diseñador/a de moda',
    'Modelo',
    'Personal shopper',
    'Estilista',
    'Fotógrafo/a de moda',
  ],
  Construcción: [
    'Arquitecto/a',
    'Ingeniero/a civil',
    'Albañil',
    'Carpintero/a',
    'Electricista',
  ],
  Automoción: [
    'Mecánico/a de automóviles',
    'Ingeniero/a automotriz',
    'Diseñador/a de automóviles',
    'Chapista',
    'Vendedor/a de autos',
  ],
  Finanzas: [
    'Contador/a',
    'Analista financiero/a',
    'Asesor/a financiero/a',
    'Gestor/a de inversiones',
    'Economista',
  ],
  'Medio Ambiente': [
    'Biólogo/a',
    'Ingeniero/a ambiental',
    'Ecologista',
    'Consultor/a ambiental',
    'Geólogo/a',
  ],
  Turismo: [
    'Agente de viajes',
    'Guía turístico/a',
    'Recepcionista de hotel',
    'Gestor/a de eventos',
    'Camarero/a de cruceros',
  ],
  'Cine y TV': [
    'Director/a de cine',
    'Actor/actriz',
    'Guionista',
    'Productor/a de televisión',
    'Editor/a de vídeo',
  ],
  Música: ['Músico/a', 'Cantante', 'Productor/a musical', 'Compositor/a', 'DJ'],
  Marketing: [
    'Especialista en SEO',
    'Especialista en SEM',
    'Community manager',
    'Analista de mercado',
    'Director/a de marketing',
  ],
  Consultoría: [
    'Consultor/a de negocios',
    'Consultor/a de gestión',
    'Consultor/a de tecnología',
    'Consultor/a financiero/a',
    'Consultor/a de recursos humanos',
  ],
  'Recursos Humanos': [
    'Gestor/a de talento',
    'Especialista en reclutamiento',
    'Analista de recursos humanos',
    'Entrenador/a de desarrollo',
    'Responsable de nóminas',
  ],
  'Servicios Legales': [
    'Abogado/a',
    'Notario/a',
    'Juez/a',
    'Fiscal',
    'Asesor/a jurídico/a',
  ],
  Investigación: [
    'Investigador/a científico/a',
    'Analista de datos',
    'Epidemiólogo/a',
    'Investigador/a de mercado',
    'Analista de inteligencia',
  ],
  Otro: [
    'Otra profesión 1',
    'Otra profesión 2',
    'Otra profesión 3',
    'Otra profesión 4',
    'Otra profesión 5',
  ],
}

export default profesionesPorRubro
