const rubros = [
  'Asesoramiento Contable y Legal',
  'Belleza y Cuidado Personal',
  'Comunicacion y Diseño',
  'Cursos y Clases',
  'Fiestas y Eventos',
  'Fotografia Musica y Cine',
  'Hogar y Construccion',
  'Servicios Automotor',
  'Medicina y Salud',
  'Ropa y Moda',
  'Servicios Para Mascotas',
  'Servicios Para Oficinas',
  'Tecnologia',
  'Transporte',
  'Viajes y Turismo',
  'Educacion',
  'Gastronomia',
  'Arte',
  'Deporte',
  'Finanzas',
  'Medio Ambiente',
  'Musica',
  'Marketing',
  'Consultoria',
  'Recursos Humanos',
  'Investigacion',
]

export default rubros
