name: Sync Repos

on:
  schedule:
    - cron: '0 0 * * *' # Corre todos los días a medianoche UTC
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub Actions

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout personal repo
        uses: actions/checkout@v2

      - name: Checkout company repo
        uses: actions/checkout@v2
        with:
          repository: Securityandsystem/NetExpertos
          ref: dev
          path: empresa-repo
          token: ${{ secrets.PAT_TOKEN }}

      - name: Copy frontend directory
        run: |
          rsync -av --delete empresa-repo/frontend/ frontend/

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add frontend
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Sync frontend from empresa repo"
            # Configura la URL remota para incluir el token
            git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Nejca13/netexpertos.git
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
